openapi: 3.0.1
info:
  title: Letuce Backend API
  description: API para gerenciar clientes com suporte a CRUD e exclusão lógica.
  version: 1.0.0
servers:
  - url: https://<api-id>.execute-api.<region>.amazonaws.com
    description: API Gateway endpoint

paths:
  /customers:
    post:
      summary: Cria um novo cliente
      operationId: createCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customerId:
                  type: string
                  description: ID único do cliente.
                  example: "12345"
                nome:
                  type: string
                  description: Nome completo do cliente.
                  example: "João da Silva"
                email:
                  type: string
                  description: E-mail do cliente.
                  example: "joao@example.com"
                cpfCnpj:
                  type: string
                  description: CPF ou CNPJ do cliente.
                  example: "12345678901"
                dataNascimento:
                  type: string
                  format: date
                  description: Data de nascimento do cliente.
                  example: "1990-01-01"
                endereco:
                  type: string
                  description: Endereço do cliente.
                  example: "Rua das Flores, 123"
                contatos:
                  type: array
                  description: Lista de contatos do cliente.
                  items:
                    type: object
                    properties:
                      descricao:
                        type: string
                        example: "Residencial"
                      telefone:
                        type: string
                        example: "(11) 1111-1111"
                habilitado:
                  type: boolean
                  description: Indica se o cliente está habilitado.
                  example: true
                observacao:
                  type: string
                  description: Observação sobre o cliente.
                  example: "Cliente VIP"
                sacLider:
                  type: string
                  description: Nome do SAC líder associado ao cliente.
                  example: "Sim"
      responses:
        '201':
          description: Cliente criado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  customer:
                    type: object
                    additionalProperties: true
        '400':
          description: Dados inválidos.
    get:
      summary: Obtém a lista de clientes
      operationId: listCustomers
      responses:
        '200':
          description: Lista de clientes não excluídos logicamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  customers:
                    type: array
                    items:
                      type: object
                      additionalProperties: true
        '500':
          description: Erro interno do servidor.

  /customers/{id}:
    get:
      summary: Obtém um cliente pelo ID
      operationId: getCustomer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID do cliente.
          example: "12345"
      responses:
        '200':
          description: Cliente encontrado.
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '404':
          description: Cliente não encontrado.
    put:
      summary: Atualiza um cliente
      operationId: updateCustomer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID do cliente.
          example: "12345"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  example: "João Atualizado"
                email:
                  type: string
                  example: "joao.atualizado@example.com"
                cpfCnpj:
                  type: string
                  example: "12345678901"
                dataNascimento:
                  type: string
                  format: date
                  example: "1990-01-01"
                endereco:
                  type: string
                  example: "Rua das Palmeiras, 456"
                contatos:
                  type: array
                  items:
                    type: object
                    properties:
                      descricao:
                        type: string
                        example: "Comercial"
                      telefone:
                        type: string
                        example: "(22) 2222-2222"
                habilitado:
                  type: boolean
                  example: false
                observacao:
                  type: string
                  example: "Alteração recente"
                sacLider:
                  type: string
                  example: "Não"
      responses:
        '200':
          description: Cliente atualizado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Dados inválidos.
        '404':
          description: Cliente não encontrado.
    delete:
      summary: Exclui um cliente logicamente
      operationId: deleteCustomer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID do cliente.
          example: "12345"
      responses:
        '200':
          description: Cliente excluído logicamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Customer deleted logically"
        '404':
          description: Cliente não encontrado.
