openapi: 3.1.0
info:
  title: Letuce Backend API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: "Say hello"
      operationId: sayHello
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
