### Requisição GET com Header "token"
GET https://h5qxh4dth8.execute-api.sa-east-1.amazonaws.com/prod/hello
Authorization: de

### Requisição GET com Header "Authorization
GET https://h5qxh4dth8.execute-api.sa-east-1.amazonaws.com/prod/customers
Authorization: allow

### Requisição POST para criar um cliente
POST https://h5qxh4dth8.execute-api.sa-east-1.amazonaws.com/prod/customers
Authorization: allow
Content-Type: application/json

{
    "nome": "João da Silva ",
    "email": "joao@example.com",
    "cpfCnpj": "12345678901",
    "dataNascimento": "1990-01-01",
    "endereco": "Rua das Flores, 123",
    "habilitado": true
}

### Requisição GET para buscar um cliente
GET https://h5qxh4dth8.execute-api.sa-east-1.amazonaws.com/prod/customers/01936e38-7f75-77bf-a91f-93692fa71d69
Authorization: allow


### Requisição GET com Header "Authorization
GET https://h5qxh4dth8.execute-api.sa-east-1.amazonaws.com/prod/suppliers
Authorization: allow